# Generated by Django 5.1.7 on 2025-04-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_new', '0002_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
