# Generated by Django 5.1.7 on 2025-04-06 15:54

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_search_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to=listings.models.listing_image_path),
        ),
    ]
