# Generated by Django 5.1.7 on 2025-04-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listingimage_is_primary_alter_listingimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
