# Generated by Django 5.1.7 on 2025-04-11 06:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
